name: 'github_actions_toolkit'
description: 'A collection of github actions'
author: 'u/garronej'
inputs:
  action_name:
    required: true
    description: 'Action to run, one of: "get_package_json_version", "dispatch_event", "update_changelog", "sync_package_and_package_lock_version", "submit_module_on_deno_land", "is_well_formed_and_available_module_name"'
  owner:
    required: false
    description: 'Repository owner, example: ''garronej'',github.repository_owner'
  repo:
    required: false
    description: 'Repository name, example: ''evt'', github.event.repository.name'
  event_type:
    required: false
    description: 'see: https://developer.github.com/v3/repos/#create-a-repository-dispatch-event'
  client_payload_json:
    required: false
    description: 'Example ''{"p":"foo"}'' see: https://developer.github.com/v3/repos/#create-a-repository-dispatch-event'
  branch:
    required: false
    description: 'Example: master ( can also be a sha )'
  branch_behind:
    required: false
    description: 'Name of a branch, example: ''master'' ( can also be an sha )'
  branch_ahead:
    required: false
    description: 'Name of a branch, example: ''dev'' ( can also be an sha )'
  commit_author_email:
    required: false
    description: 'Email id  of the bot that will author the commit for updating the CHANGELOG.md file, ex: denoify_ci@github.com'
  exclude_commit_from_author_names_json:
    required: false
    description: 'For update_changelog, do not includes commit from user certain committer in the CHANGELOG.md, ex: ''["denoify_ci"]'''
  module_name:
    required: false
    description: 'A candidate module name, Example: lodash'
outputs:
  version:
    description: 'Output of get_package_json_version'
  is_valid_node_module_name:
    description: 'true|false'
  is_valid_deno_module_name:
    description: 'true|false'
  is_available_on_npm:
    description: 'true|false'
  is_available_on_deno_land:
    description: 'true|false'
  was_already_published:
    description: 'true|false'
runs:
  using: 'node12'
  main: 'dist/index.js'